### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by Jay-Krish** [Yarl-IT-Hub/ySchool#10]
BUILD FAILURE
nested exception is java.lang.NoClassDefFoundError: com/felees/hbnpojogen/persistence/GenericDAO
    at org.springframework.beans.factory.support.AbstractBeanFactory.resolveBeanClass(AbstractBeanFactory.java:1144)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.predictBeanType(AbstractAutowireCapableBeanFactory.java:524)
    at org.springframework.beans.factory.support.AbstractBeanFactory.isFactoryBean(AbstractBeanFactory.java:1177)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:222)
    at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:505)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:362)
    at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:255)
    at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:199)
    at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:45)
    at org.mortbay.jetty.handler.ContextHandler.startContext(ContextHandler.java:549)
.......
.....

**Comment by Jay-Krish** [comment]
Found the reason

yschool-ui pom files uses lite_repo as a dependency.
lite_repo pom has local file access for felees 

---

```
    <dependency>
        <groupId>com.felees</groupId>
        <artifactId>hbnpojogen-persistence</artifactId>
        <version> 1.4.4</version>
        <scope>system</scope>
        <systemPath>${basedir}/hbnPojoGenResource/hbnpojogen-persistence-1.4.4.jar</systemPath>
    </dependency>
```

---

so the transitive dependency by yschool-ui cann't be resolved due to this local access, and this causes all the slf4j and spring annotation missing...
I solved it by placing hbnpojogen-persistence jar into .m2 and remove the local access from pom.
One solution would be to host com.felees and refer it from <dependency> tag.

**Comment by kanarupan** [comment]
As a temporary solution:

First run the command from base directory (or from anywhere with the care on ''-Dfile=$Path")

mvn install:install-file -Dfile=modules\lite_repo\hbnPojoGenResource\hbnpojogen-persistence-1.4.4.jar -DgroupId=com.felees -DartifactId=hbnpojogen-persistence -Dversion=1.4.4 -Dpackaging=jar

then run Maven command from the super pom.xml level
mvn clean install

go inside of the yschool module (yschool/yschool) and run command, to start the jetty server
mvn clean jetty:run-war

open, localhost:8080/yschool 

...and it should work!

**Comment by Jay-Krish** [comment]
closing the failure issue as there is a temporary solution
opened a defect #13 to deal with felees artifact missing issue.
